### ISSUE TITLE
Almura 3.0 - Todo Feature List

### ISSUE THREAD

**Issue by Dockter** [AlmuraDev/Almura#371]
The following is a list of features that Almura 2.5 has that need to be restored in Almura 3.0
- [x] Backpack - replaced with IronBackpacks.
- [ ] Custom block and item
- [ ] Custom crops
- [ ] Custom trees
- [ ] Accessories (Wings, hats, rings etc)
- [ ] Custom player titles.
- [ ] Infoguide (may be a separate plugin)
- [ ] Custom respawn / revive abilities on player death.
- [ ] Lose money on Player Death.
- [ ] Custom currency's (copper, silver, gold, platinum) coins.  Exchangeable for in-game money.
- [ ] Almura Banking system (existed early on in Almura 1.0)
- [ ] Stack-able water buckets, lava buckets, water bottles and glass jars. 
- [x] DocEnchant - replaced by Nucleus.
- [ ] Recipes that except multiple quantities for a single produced item.

The following were planned features but never finished or were features based on Bukkit plugins:
- [ ] Custom armor, weapons and tools.
- [ ] Custom Sounds (Kashike already working on this)
- [ ] Custom particles
- [ ] Crop regrowth.
- [ ] Jump height, run speed modifier for custom blocks
- [ ] Safe block, secure storage box that is locked to that user ONLY.
- [ ] Treasure Chests (was part of a Bukkit Treasure Chest Plugin)
- [ ] Repair Shop (was part of a Bukkit Plugin)
- [ ] Unique player inventories based on world configuration file (like backpack's share ability)

**Comment by Dockter** [comment]
I've broken this issue up into 4 different release schedule issues.
