### ISSUE TITLE
Almura 3.0 - Release 1 - Goal: 10/1/2018

### ISSUE THREAD

**Issue by Dockter** [AlmuraDev/Almura#379]
The following is a list of functionalities that is required for Release 1:

**Content Loader for:**

*Blocks:*
- [x] Normal Blocks
- [x] Horizontal Blocks
- [x] Crop Blocks
- [x] Stairs
- [x] Slabs
- [x] Container Blocks (Chests)
- [x] Caches

*Crops:*
- [x] Biome / Climate consideration
- [x] Death due to crop being too cold

*Items:*
- [x] Normal Items
- [x] Seed Items
- [x] Food Items
- [x] Custom Farm Tools
- [x] Stackable Water and Potion bottles.
- [x] Stackable buckets to 64.
- [x] ItemReturn Handler -> For Glass bottles mostly when used in Drinks.

*Complex Items:*
- [x] World Light Fix Wand
- [x] Farmers Almanac (Mostly Completed)

*Complex Blocks:*
- [x] Coin Exchange

*Complex Addons:*
- [x] Database Back-end
- [x] Guide
- [x] Grief Prevention linked HUD
- [x] Skills
- [x] Stores
- [x] Exchange
- [x] World Generation
- [x] Title Manager
- [x] Nickname Manager
- [x] Animal Breeding Status
- [x] Sign Optimizations and Editing
- [x] Notifications System
- [x] Player/Animal/Mob Healthbar System

**GUI System**
- [x] Platinum/Gold/Silver/Copper based currency system

*Other:*
- [x] Trees (Wood blocks are implemented, Leaves are not, fruit is not)
- [x] Saplings
- [x] Crop/Flower in World Generator (Patched using Mixin to various generators including TerrainControl)
- [x] Saplings included in Generator (Ready once Saplings are done)

**GUI functions:**
- [x] When using the Almanac, if you (right click a Strawberry) (or anything that needs to make the property Container scroll), the window area doesn't scroll via the mouse wheel.
- [x] New Origin HUD design implementation
- [x] Toggle ability for each Origin hud applet (Top Left, Middle, Right)
- [x] Currency display.
- [x] In-Game Guide System (view only is fine)
- [x] Custom Server GUI (Mimic Almura 2.5)
- [x] In-game explanation of the Origin HUD system.
- [x] Notification area added above the World Name/ Compass Widget.

**Paydirt Washplant**
- [x] GUI render errors
- [x] TE SINK values are incorrect at the client
- [x] Some values appear negative values which should be impossible

**Server Issues:**
- [x] Spawn Chunks are not unloading.  (Keep-Loaded branch in SpongeForge resolves issue).
- [x] IC2 TileEntities are being destroyed if a blockBreak action is prevented.
- [x] View Distance [Sponge Issue](https://github.com/SpongePowered/SpongeAPI/issues/1658) is not configurable per world.

**GitHub Issues:**
- [x] [GUI - Changes](https://github.com/AlmuraDev/Almura/issues/361)
- [x] [GUI - Decimal Spots](https://github.com/AlmuraDev/Almura/issues/364)
- [x] [Content Loader - Model Cracking Animation](https://github.com/AlmuraDev/Almura/issues/309)
- [x] [Content Loader - Attributes](https://github.com/AlmuraDev/Almura/issues/315)
- [x] [Content Loader - Actions](https://github.com/AlmuraDev/Almura/issues/340)
- [x] [Content Loader - Recipe Conflict](https://github.com/AlmuraDev/Almura/issues/222)

**Comment by Dockter** [comment]
Server GUI in place.

**Comment by Dockter** [comment]
Dynmap w/Grief Prevention is now functional.

**Comment by liach** [comment]
Seems Railcraft is the one that hampers progress, but I can hardly help

**Comment by Dockter** [comment]
Liach, is Railcraft ever going to update or should I count on not including that with Release 1?

**Comment by liach** [comment]
Try not including that for the first release. It will be very long (we've done nothing on recipes yet)

**Comment by Dockter** [comment]
Recipes are actually pretty easy to convert.  I need Railcraft in otherwise I'll be missing ores during world-gen.

**Comment by liach** [comment]
I suggest you approaching @CovertJaguar by emailing to covertjaguar@gmail.com or tagging him on twitter.

**Comment by Dockter** [comment]
I'm going to do the HUD explanation in a guide.

**Comment by Zidane** [comment]
@Dockter I marked saplings in generator as checked because we want the trees to be in generator instead and you're working on this right now.

**Comment by liach** [comment]
So there are accessories, banking system, and stores still in progress? You should really track these with github milestones.

**Comment by Dockter** [comment]
The last module I wanted for Release 1 has been completed thanks to @Grinch and @Zidane.  I will be working to go into full release mode very shortly.
