### ISSUE TITLE
Almura 3.0 - Release 1.5 - Long-Term Bug Fixes

### ISSUE THREAD

**Issue by Dockter** [AlmuraDev/Almura#470]
This is a mid-point update from 1.0 to 2.0.  This is intended to be a mostly bug fix / progressive update.

The following functionalities are planned for Almura 3.0 - Release 1.5

**CORE**
- [ ] Add ServerConfig for turning modules on/off

**GUI System**
- [x] [Mouse doesn't unlock when GUI's open](https://github.com/AlmuraDev/Almura/issues/412)
- [ ] Player Accessories
- [ ] Banking System

**Content Loader**
- [x] Crop OBJ rotation errors
- [ ] Implement "BurnTime" for furnace abilities
- [ ] Implement 2x2 Tree Feature
- [ ] Add fruit/hanging fruit regrow mechanism to Trees

**Bucket Feature**
- [ ] [Stackable Buckets Feature causing conflicts](https://github.com/AlmuraDev/Almura/issues/463)

**Animal Breeding**
- [x] [Re-Implement ability to breeding Twins](https://github.com/AlmuraDev/Almura/issues/396)
- [x] [Re-Implement ability to see animal HEAT](https://github.com/AlmuraDev/Almura/issues/388)

**TerrainControl**
- [x] Client Biome implementation
- [ ] [Biome Coloring wrong on client](https://github.com/AlmuraDev/Almura/issues/461)
- [x] [BigTree Generation Error](https://gist.github.com/Dockter/56be6a5505ded3717ffa306793f077f9)

**CustomMobSpawner**
- [x] [Conflict with Sponge](https://gist.github.com/Dockter/3aeba95add8df7fc1889f31907190027)

**Comment by Dockter** [comment]
I have implemented the burntime feature by doing a overwrite mixing within TileEntityFurnace.

**Comment by liach** [comment]
Can you add "tool class check for effective tools" into this list?

**Comment by Dockter** [comment]
The OBJ rotation issue with crops is resolved by using two textures for the models cross section.

**Comment by Dockter** [comment]
Moved to combined feature issue.
