### ISSUE TITLE
[Feature] Exchange - Beta Checklist

### ISSUE THREAD

**Issue by Zidane** [AlmuraDev/Almura#488]
Exchange is getting close to prime time for inclusion into the Almura mod for a time and released to the masses at a later date. In the interim, the following is a rough TODO before I'll sign it off for beta candidacy.

- [ ] Finish up notification TODOs in ServerExchangeManager.
- [ ] Handle "refund" if database insertion fails when listing a new item. I'll need to give it back to their inventory. If we cannot give them all of the item, alert the console and the admin and the player can sort it out.
- [x] Handle giving them the items back after purchase if they went offline. If we cannot give them all of the item, alert the console and the admin and the player can sort it out.
- [x] Change purchase to deduct the cash right away from the buyer.
  - [ ] Once done, handle "refund" if database transaction fails. We need to refund the buyer their money.
- [x] Handle slot limit upgrades. Dockter is thinking a "step up" system via commands.
- [x] Rigorous testing. If bugs are found, I want clear and concise instructions on how to reproduce. The inventory logic in this mod is complex.
