### ISSUE TITLE
Almura 3.x - Features / Todo List

### ISSUE THREAD

**Issue by Dockter** [AlmuraDev/Almura#541]
**In Development Builds**
- [Almura 3.1 / b100](https://github.com/AlmuraDev/ServerConfig/issues/15)

### In Development Features & ToDo's

**Priority Bugs** / [User Reported Issues](https://github.com/AlmuraDev/GameServer/issues)
- [ ] Glass Cruets need to implement iFluid - [Ticket](https://github.com/AlmuraDev/GameServer/issues/55) - [Example](https://gist.github.com/jabelar/73e47e4bf57e977b04c0c94048730f72)

**Crop System**
- [ ] Harvest crop without re-planting (custom tool?)
- [ ] Crop re-growth
- [ ] Companion crops.  Certain crops grow better when near others.
- [ ] Cross-plant pollination.
- [x] Fruit Tree - Regrow Fruit without replanting tree

**Complex Features**
- [ ] Global discovery database
- [ ] [Collections System](https://github.com/AlmuraDev/Almura/issues/527)
- [ ] Treasure Chests (Maybe use mod)
- [ ] Player Accessories
- [ ] Banking System
- [ ] [Stackable Buckets Feature causing conflicts](https://github.com/AlmuraDev/Almura/issues/463)
- [ ] [Scoreboard](https://github.com/AlmuraDev/Almura/issues/350)

**Admin Abilities**
- [ ] GUI screen to show Player, Nickname, world and location.

**GUI System**
- [ ] Add/Edit/Remove personal guides
- [ ] [Clientside Hud Cache](https://github.com/AlmuraDev/Almura/issues/532)
- [x] [Exchange - Admin Delist](https://github.com/AlmuraDev/Almura/issues/501)
- [x] [Exchange - Item Delist](https://github.com/AlmuraDev/Almura/issues/524)
- [ ] [Exchange - Hide Self from Listing / Search](https://github.com/AlmuraDev/Almura/issues/521)
- [ ] [Exchange - Internal Changes](https://github.com/AlmuraDev/Almura/issues/488)
- [ ] [Store - Changes](https://github.com/AlmuraDev/Almura/issues/529)
- [ ] [Guide Backend Changes](https://github.com/AlmuraDev/Almura/issues/513)

**Content Loader**
- [ ] Custom blocks and objects with custom animations
- [ ] Jump and runspeed modifiers
- [ ] Custom particles support
- [ ] Custom sounds
- [ ] Custom armor and weapons
- [ ] [ItemReturns](https://github.com/AlmuraDev/Almura/issues/471)
- [ ] [Expose Priority Feature in Loader](https://github.com/AlmuraDev/Almura/issues/446)
- [ ] [Advanced Features](https://github.com/AlmuraDev/Almura/issues/436)
